### PR TITLE
feat: Add new default IANA TA

### PR DESCRIPTION
**Pull request by veegishx**
# What kind of change does this PR introduce?
The new IANA TA which is expected to start working in 2026
https://data.iana.org/root-anchors/root-anchors.xml

# What is the current behavior? 
N/A

# What is the new behavior (if this is a feature change)?
N/A

### CODE REVIEW

**Comment by gnarea** [comment]
Thank you so much @veegishx!! 🙇🏾 

Everything looks good to me, but CI is failing due to [something unrelated to this PR](https://github.com/hildjj/dohdec/pull/38#issuecomment-2323411153) -- I'm going to fix it and then I'll merge this PR.

**Comment by gnarea** [comment]
Thanks for your patience @veegishx! We've just fixed the issue that was blocking this PR. Can you please merge/rebase the latest commits from the `main` branch? I'd do it myself but I don't want write permissions to your branch. Once you do that, I'll re-approve this PR and merge it.

**Review by gnarea — APPROVED** [review]
Thanks!

**Comment by veegishx** [comment]
Hello @gnarea ,changes merged!

**Pull request merged**
